config/routes.rb
Serooskerke::Application.routes.draw do

  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :comments
  resources :events

  resources :surroundings do
  	resources :photos
  end

  devise_for :admins

  resources :impressions do
  	resources :pictures
  end

  get "pages/home"

  root 'pages#home'

  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create', :via => :post
end

app/models/impression.rb
class Impression < ActiveRecord::Base
	has_many :pictures
	accepts_nested_attributes_for :pictures
	belongs_to :admin
end

app/controllers/impressions_controller.rb
class ImpressionsController < ApplicationController
  before_action :set_impression, only: [:edit, :update]
  before_filter :authenticate_admin!, except: [:show]

  def index
    @impressions = Impression.all
  end

  def show
    @impressions = Impression.all
    @impression = Impression.find(params[:id])
    @pictures = @impression.pictures
    @picture_groups = @pictures.in_groups_of(3, false)

  end

  # GET /impressions/new
  def new
    @impression = Impression.new
  end

  # GET /impressions/1/edit
  def edit
  end

  # POST /impressions
  # POST /impressions.json
  def create
    @impression = Impression.new(impression_params)

    respond_to do |format|
      if @impression.save
        format.html { redirect_to @impression, notice: 'Impression was successfully created.' }
        format.json { render action: 'show', status: :created, location: @impression }
      else
        format.html { render action: 'new' }
        format.json { render json: @impression.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @impression.update(impression_params)
        format.html { redirect_to @impression, notice: 'Impression was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @impression.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_impression
      @impression = Impression.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def impression_params
      params[:impression].permit(:title, :description)
    end
end

app/helpers/impressions_helper.rb
module ImpressionsHelper
end

app/views/impressions/_form.html.erb
<%= simple_form_for(@impression) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :title, label: 'Voeg titel toe:' %>
    <%= f.input :description, label: 'Voeg omschrijving toe', as: :text %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/impressions/edit.html.erb
<h1>Editing impression</h1>

<%= render 'form' %>

<%= link_to 'Show', @impression %> |
<%= link_to 'Back', impressions_path %>

app/views/impressions/index.html.erb
<h1>Listing impressions</h1>

    <% @impressions.each do |impression| %>
      
        <p><%= impression.title %></p>
        <p><%= impression.description %></p>
        <%= link_to 'Show', impression %>
        <%= link_to 'Edit', edit_impression_path(impression) %>
        <%= link_to 'Destroy', impression, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

<br>

<%= link_to 'New Impression', new_impression_path %>

app/views/impressions/new.html.erb
<h1>New impression</h1>

<%= render 'form' %>

<%= link_to 'Back', impressions_path %>

app/views/impressions/show.html.erb
<p id="notice"><%= notice %></p>
<div id="primary" class="site-content">
  <div id="content" role="main">

    <% @impressions.each do |impression| %>

      <article id="post-5" class="post-5 page type-page status-publish hentry">
        <header class="entry-header">
          <h1 class="entry-title"><%= impression.title %></h1>
        </header>
        <div class="entry-content">
          <p><%= impression.description %></p>
          <% if admin_signed_in? %>
          <p><%= link_to 'Pas bovenstaande tekst aan.', edit_impression_path(@impression) %></p>
          <% end %>
        </div>
      </article>
    <% end %>
  </div>  


  <div id="blog">
    <div class="container">
      <div class="section_header">
        <h3>Foto's</h3>
      </div>
      <% @picture_groups.each do |pictures| %>
        <div class="row post_row">
          <% pictures.each_with_index do |picture, i| %>
            <div class="span4 post <%= check_for_last_class(i) %>">
              <div class="img">
                <%= link_to (image_tag picture.image(:medium)), picture.image(:original), rel: "prettyPhoto", title: picture.title %>            
              </div>
              <div class="text">
                <%= truncate(picture.title, length: 30) %>
              </div>
              <% if admin_signed_in? %>
              <div class="author_box"> 
                <p><%= link_to 'Edit', edit_impression_picture_path(@impression, picture) %>
                <%= link_to 'Destroy', [@impression, picture], data: { confirm: 'Are you sure?' },
                                  :method => :delete %></p>
              </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>   
    </div>
  </div>
<% if admin_signed_in? %>
<p><%= link_to 'Nieuwe foto toevoegen', new_impression_picture_path(@impression) %></p>
<% end %>
</div>