config/routes.rb
Serooskerke::Application.routes.draw do

  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :comments
  resources :events

  resources :surroundings do
  	resources :photos
  end

  devise_for :admins

  resources :impressions do
  	resources :pictures
  end

  get "pages/home"

  root 'pages#home'

  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create', :via => :post
end

app/models/surrounding.rb
class Surrounding < ActiveRecord::Base
	has_many :photos
	accepts_nested_attributes_for :photos
	belongs_to :admin
end

app/controllers/surroundings_controller.rb
class SurroundingsController < ApplicationController
  before_action :set_surrounding, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, except: [:show]

  # GET /surroundings
  # GET /surroundings.json
  def index
    @surroundings = Surrounding.all
  end

  # GET /surroundings/1
  # GET /surroundings/1.json
  def show
    @surroundings = Surrounding.all
    @surrounding = Surrounding.find(params[:id])
    @photos = @surrounding.photos    
    @photo_groups = @photos.in_groups_of(3, false)

  end

  # GET /surroundings/new
  def new
    @surrounding = Surrounding.new
  end

  # GET /surroundings/1/edit
  def edit
  end

  # POST /surroundings
  # POST /surroundings.json
  def create
    @surrounding = Surrounding.new(surrounding_params)

    respond_to do |format|
      if @surrounding.save
        format.html { redirect_to '/surroundings/1/', notice: 'Surrounding was successfully created.' }
        format.json { render action: 'show', status: :created, location: @surrounding }
      else
        format.html { render action: 'new' }
        format.json { render json: @surrounding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surroundings/1
  # PATCH/PUT /surroundings/1.json
  def update
    respond_to do |format|
      if @surrounding.update(surrounding_params)
        format.html { redirect_to '/surroundings/1/', notice: 'Surrounding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @surrounding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surroundings/1
  # DELETE /surroundings/1.json
  def destroy
    @surrounding.destroy
    respond_to do |format|
      format.html { redirect_to '/surroundings/1/' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surrounding
      @surrounding = Surrounding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def surrounding_params
      params.require(:surrounding).permit(:title, :description)
    end
end

app/helpers/surroundings_helper.rb
module SurroundingsHelper
end

app/views/surroundings/_form.html.erb
<%= simple_form_for(@surrounding) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :title, label: 'Voeg titel toe:' %>
    <%= f.input :description, label: 'Voeg omschrijving toe', as: :text %>
  </div>

  <div class="actions">
    <%= f.button :submit, 'Pas aan!' %>
  </div>
<% end %>

app/views/surroundings/edit.html.erb
<h1>Bewerk tekst.</h1>

<%= render 'form' %><br>

<%= link_to 'Terug', '/surroundings/1/' %>

app/views/surroundings/index.html.erb
<h1>Listing surroundings</h1>

    <% @surroundings.each do |surrounding| %>
      
        <p><%= surrounding.title %></p>
        <p><%= surrounding.description %></p>
        <%= link_to 'Show', surrounding %>
        <%= link_to 'Edit', edit_surrounding_path(surrounding) %>
        <%= link_to 'Destroy', surrounding, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>

<br>

<%= link_to 'New Surrounding', new_surrounding_path %>

app/views/surroundings/new.html.erb
<h1>New surrounding</h1>

<%= render 'form' %>

<%= link_to 'Back', surroundings_path %>

app/views/surroundings/show.html.erb
<p id="notice"><%= notice %></p>
<div id="primary" class="site-content">
  <div id="content" role="main">

    <% @surroundings.each do |surrounding| %>

      <article id="post-5" class="post-5 page type-page status-publish hentry">
        <header class="entry-header">
          <h1 class="entry-title"><%= surrounding.title %></h1>
        </header>
        <div class="entry-content">
          <p><%= surrounding.description %></p>
          <% if admin_signed_in? %>
          <p><%= link_to 'Pas bovenstaande tekst aan.', edit_surrounding_path(@surrounding) %></p>
          <% end %>
        </div>
      </article>
    <% end %>
  </div>  


  <div id="blog">
    <div class="container">
      <div class="section_header">
        <h3>Foto's</h3>
      </div>
      <% @photo_groups.each do |photos| %>
        <div class="row post_row">
          <% photos.each_with_index do |photo, i| %>
            <div class="span4 post <%= check_for_last_class(i) %>">
              <div class="img">
                <%= link_to (image_tag photo.image(:medium)), photo.image(:original), rel: "prettyPhoto", title: photo.title %>            
              </div>
              <div class="text">
                <%= truncate(photo.title, length: 30) %>
              </div>
              <% if admin_signed_in? %>
              <div class="author_box"> 
                <p><%= link_to 'Edit', edit_surrounding_photo_path(@surrounding, photo) %>
                <%= link_to 'Destroy', [@surrounding, photo], data: { confirm: 'Are you sure?' },
                                  :method => :delete %></p>
              </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>   
    </div>
  </div>
<% if admin_signed_in? %>
<p><%= link_to 'Nieuwe foto toevoegen', new_surrounding_photo_path(@surrounding) %></p>
<% end %>
</div>