config/routes.rb
Serooskerke::Application.routes.draw do

  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :comments
  resources :events

  resources :surroundings do
  	resources :photos
  end

  devise_for :admins

  resources :impressions do
  	resources :pictures
  end

  get "pages/home"

  root 'pages#home'

  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create', :via => :post
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :impression
	belongs_to :admin

	has_attached_file :image, styles: { medium: "320x240#"}
  validates_attachment :image, presence: true,
                        content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                        size: { less_than: 5.megabytes }

  validates :title, presence: true
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :get_impression
  before_filter :authenticate_admin!, except: [:index]
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = @impression.pictures
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = @impression.pictures.find(params[:id])
  end

  # GET /pictures/new
  def new
    @impression = Impression.find(params[:impression_id])
    @picture = @impression.pictures.build
  end

  # GET /pictures/1/edit
  def edit
    @impression = Impression.find(params[:impression_id])
    @picture = @impression.pictures.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = @impression.pictures.build(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to '/impressions/1/', notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    @picture = @impression.pictures.find(params[:id])

    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to '/impressions/1/', notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = @impression.pictures.find(params[:id])
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to '/impressions/1/' }
      format.json { head :no_content }
    end
  end

  private

    def get_impression
      @impression = Impression.find(params[:impression_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :impression_id, :image)
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<%= simple_form_for([@impression, @picture]) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size %>
  <%= f.full_error :image_content_type %>

  <% if @impression %>
    <input type="hidden" name="picture[impression_id]" value="<%= @impression.id %>" />
  <% end %>

  <div class="inputs">
    <%= f.input :image, label: 'Voeg afbeelding toe', rel: ["prettyPhoto[pp_gal"] %>
    <%= f.input :title, label: 'Voeg een omschrijving van de foto toe' %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Foto aanpassen.</h1>

<%= render 'form' %>

<%= link_to 'Back', impression_pictures_path(@impression) %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= link_to (image_tag picture.image(:medium)), [@impression, picture] %></td>
        <%= link_to 'Show', [@impression, picture] %>
        <%= link_to 'Edit', edit_impression_picture_path(@impression, picture) %>
        <%= link_to 'Destroy', [@impression, picture], :confirm => 'Are you sure?',
                  :method => :delete %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_impression_picture_path %>

app/views/pictures/new.html.erb
<h1>Nieuwe foto toevoegen.</h1>

<%= render 'form' %>

<%= link_to 'Back', impression_pictures_path(@impression) %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

	<%= link_to 'Edit', edit_impression_picture_path(@impression, @picture) %>
	<%= link_to 'Back', impression_pictures_path(@impression) %>