config/routes.rb
Serooskerke::Application.routes.draw do

  get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  resources :comments
  resources :events

  resources :surroundings do
  	resources :photos
  end

  devise_for :admins

  resources :impressions do
  	resources :pictures
  end

  get "pages/home"

  root 'pages#home'

  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create', :via => :post
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
	has_many :events
	accepts_nested_attributes_for :events
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	has_attached_file :image, styles: { medium: "320x240#"}
  validates_attachment :image, 
                        content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                        size: { less_than: 5.megabytes }

  validates :name, presence: true
  validates :title, presence: true
	validates :message, presence: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :calendar
  has_event_calendar
  belongs_to :admin

  # To specify the columns to use call it like this:
  # 
  # has_event_calendar :start_at_field  => 'custom_start_at', :end_at_field => 'custom_end_at'
  # 
  
end

app/models/impression.rb
class Impression < ActiveRecord::Base
	has_many :pictures
	accepts_nested_attributes_for :pictures
	belongs_to :admin
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :surrounding
	belongs_to :admin

	has_attached_file :image, styles: { medium: "320x240#"}
  validates_attachment :image, presence: true,
                        content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                        size: { less_than: 5.megabytes }

  validates :title, presence: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :impression
	belongs_to :admin

	has_attached_file :image, styles: { medium: "320x240#"}
  validates_attachment :image, presence: true,
                        content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                        size: { less_than: 5.megabytes }

  validates :title, presence: true
end

app/models/surrounding.rb
class Surrounding < ActiveRecord::Base
	has_many :photos
	accepts_nested_attributes_for :photos
	belongs_to :admin
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to calendar_path, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to calendar_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_at, :end_at, :all_day)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def check_for_last_class(i)
		if i == 2
			return "last"
		end
	end

end

app/helpers/calendar_helper.rb
module CalendarHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end
  
  # custom options for this calendar
  def event_calendar_opts
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>",
      :use_all_day => true,
      :first_day_of_week => @first_day_of_week
    }
  end

  def event_calendar
    # args is an argument hash containing :event, :day, and :options
    calendar event_calendar_opts do |args|
      event, day = args[:event], args[:day]
      html = %(<a href="/events/#{event.id}" title="#{h(event.name)}">)
      html << display_event_time(event, day)
      html << %(#{h(event.name)}</a>)
      html
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/impressions_helper.rb
module ImpressionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/surroundings_helper.rb
module SurroundingsHelper
end

app/views/layouts/_footer.html.erb
<footer id="colophon" role="contentinfo">
	<div class="site-info">
		<p>Voor boekingen kunt u contact opnemen met +31 6 38292352, of e-mailen naar <a class="text" href="mailto:hidskes@gmail.com">hidskes@gmail.com.</a>
		</p>
		<% if admin_signed_in? %>
		<p>
			<%= link_to 'Admin Sign Out', destroy_admin_session_path, :method => :delete %>
		</p>
		<%	else %>
		<p>
			<%= link_to 'Admin Sign In', new_admin_session_path %>
		</p>
		<% end %>
	</div><!-- .site-info -->
</footer>

app/views/layouts/_homepagebanner.html.erb
<!-- start banner -->
<div id="main" class="wrapper"><div id="slider" class="flexslider">
    
<div class="flex-viewport" style="overflow: hidden; position: relative;"><ul class="slides" style="width: 1200%; -webkit-transition: 0.6s; transition: 0.6s; -webkit-transform: translate3d(-2826px, 0, 0);">
    <li class="clone" style="width: 1413px; float: left; display: block;">
      <a href=""><img src="/assets/slide1.png" alt=""></a>
      <div class="flex-holder">
        <div class="flex-caption">
          <div>
            <h1 style="background: #43bd3d;"><a href="" style="color: #fff;">VRIJSTAAND VAKANTIEHUIS</a></h1>
            <h1 style="background: #43bd3d;"><a href="" style="color: #fff;">OP SHOUWEN-DUIVELAND</a></h1>
            <span class="flex-caption-decription">Huis van 160m<sup>2</sup> met 600m<sup>2</sup> eigen grond in het rustige Serooskerke.</span>
          </div>
        </div>
      </div>
    </li>
    <li style="width: 1413px; float: left; display: block;" class="">
      <a href="http://chaletbouquetins.nl/chalet/"><img src="/assets/slide2.jpg" alt=""></a>
      <div class="flex-holder">
        <div class="flex-caption">
          <div>
            <h1 style="background: #428cbc;"><a href="" style="color: #fff;">VIER SLAAPKAMERS</a></h1>
            <h1 style="background: #428cbc;"><a href="" style="color: #fff;">EN HUISDIEREN WELKOM</a></h1>
            <span class="flex-caption-decription">Acht slaapplekken, twee toiletten, wifi en afwasmachine aanwezig</span>
          </div>
        </div>
      </div>
    </li>
    <li class="flex-active-slide" style="width: 1413px; float: left; display: block;">
      <a href="http://chaletbouquetins.nl/chalet/"><img src="/assets/slide3.jpg" alt=""></a>
      <div class="flex-holder">
        <div class="flex-caption">
          <div>
            <h1 style="background: #d96f4e;"><a href="" style="color: #fff;">GELEGEN NABIJ</a></h1>
            <h1 style="background: #d96f4e;"><a href="" style="color: #fff;">PRACHTIGE NATUUR</a></h1>
            <span class="flex-caption-decription">Ligging aan een doodlopende weg, vlakbij het strand bij de Oosterschelde waar honden toegestaan zijn.</span>
          </div>
        </div>
      </div>
    </li>
    <li class="" style="width: 1413px; float: left; display: block;">
      <a href="http://chaletbouquetins.nl/crans-montana/"><img src="assets/slide4.jpg" alt="Ski"></a>
      <div class="flex-holder">
        <div class="flex-caption">
          <div>
              <h1 style="background: #428cbc;"><a href="" style="color: #fff;">STRAND OP LOOPAFSTAND</a></h1>
              <h1 style="background: #428cbc;"><a href="" style="color: #fff;">WANDELEN DOOR DE DUINEN</a></h1>
              <span class="flex-caption-decription">
                Diverse leuke wandel- en fietsroutes in de nabije omgeving.
              </span>
          </div>
        </div>
      </div>
    </li>

  </div>
  <ul class="flex-direction-nav">
    <li><a class="flex-prev" href="#">Previous</a></li>
    <li><a class="flex-next" href="#">Next</a></li> </ul>
</div> <!-- End of banner -->

<!-- start slider -->
<div class="carouselWrapper">
  <div class="site-content">
    <div id="carousel" class="flexsliders">
      <div class="flex-viewport" style="overflow: hidden; position: relative;">
        <ul class="slides" style="width: 800%; -webkit-transition: 0s; transition: 0s; -webkit-transform: translate3d(0px, 0, 0);">
          <li class="" style="width: 215px; float: left; display: block;"><img src="/assets/slide1_thumb.jpg" alt="Exclusief chalet"></li>
          <li class="flex-active-slide" style="width: 215px; float: left; display: block;"><img src="/assets/slide2_thumb.jpg" alt="Chalet"></li>
          <li class="" style="width: 215px; float: left; display: block;"><img src="/assets/slide3_thumb.jpg" alt="Ski"></li>
          <li style="width: 215px; float: left; display: block;" class=""><img src="/assets/slide4_thumb.jpg" alt="Golf "></li>
        </ul>
      </div>
      <ul class="flex-direction-nav">
        <li><a class="flex-prev flex-disabled" href="#">Previous</a></li>
        <li><a class="flex-next flex-disabled" href="#">Next</a></li>
      </ul>
    </div>
  </div>
</div>
<!-- end of slider -->

<script type="text/javascript">
jQuery(window).load(function() {
    jQuery('#carousel').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        itemWidth: 215,
        itemMargin: 20,
        asNavFor: '#slider'
    });
    jQuery('#slider').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: true,
        slideshow: true,
        slideshowSpeed: 4500,
        sync: "#carousel",
        start: function(slider){
            jQuery('body').removeClass('loading');
        }
    });
});
</script>

app/views/layouts/_navbar.html.erb
<header class="site-header">
  <hgroup>
		<h1 class="site-title"><%= link_to 'Vakantiewoning Serooskerke', root_path %></h1>
  </hgroup>
  <nav id="site-navigation" class="main-navigation" role="navigation">
		<div class="menu-menu-container">
			<ul id="menu-menu" class="nav-menu">
				<li id="menu-item-94"><%= link_to 'Omgeving', '/surroundings/1/', class: 'menu-item menu-item-type-post_type menu-item-object-page menu-item-94' %></li>
				<li id="menu-item-92"><%= link_to 'Indeling woning', '/impressions/1/', class: "menu-item menu-item-type-post_type menu-item-object-page menu-item-92" %></li>
				<li id="menu-item-91"><%= link_to 'Verhuur', calendar_path, class: "menu-item menu-item-type-post_type menu-item-object-page menu-item-91" %></li>
				<li id="menu-item-90"><%= link_to 'Gastenboek', comments_path, class: "menu-item menu-item-type-post_type menu-item-object-page menu-item-90" %></li>
				<li id="menu-item-93"><%= link_to 'Contact', contact_path, class: "menu-item menu-item-type-post_type menu-item-object-page menu-item-93" %></li>
			</ul>
		</div>	
	</nav><!-- #site-navigation -->
<div style="clear:both;"></div>
</header>

app/views/layouts/_navbar_extension.html.erb
<div id="main" class="wrapper">
  <header style="background: url(/assets/slide1_index.jpg) top center no-repeat;padding-bottom: 130px;padding-top: 60px;">
  </header>
</div>

app/views/layouts/_yield.html.erb
<% if current_page?(contact_path) %>
  <%= yield %>
<% elsif current_page?(root_path) %>
  <%= yield %>
<% else %>
  <div class="container">
    <%= yield %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Serooskerke</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.js" %>
  <%= javascript_include_tag "event_calendar" %>
  <%= stylesheet_link_tag "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" %>
  <%= stylesheet_link_tag "event_calendar" %>
  <%= csrf_meta_tags %>
</script>
</head>
<body>

<%= render 'layouts/navbar' %> 

<% if current_page?(root_path) %>
	<%= render 'layouts/homepagebanner' %>
<% end %>

<% unless current_page?(root_path) %>
	<%= render 'layouts/navbar_extension' %>
<% end %>

<%= render 'layouts/yield' %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<div class="container">
	<div id="fronty" class="site-content">
    <div id="content" role="main">
      <article id="post-5" class="post-5 page type-page status-publish hentry">
        <header class="entry-header">
          <h1 class="entry-title">Vakantiewoning Serooskerke</h1>
        </header>

        <div class="entry-content">
          <p>In Serooskerke op Schouwen- Duivenland verhuren we ons grote, vrijstaande vakantiehuis.
						Het huis is geschikt voor 2 – 8 personen. We verhuren het huis buiten de schoolvakanties ook per weekend of midweek. Huisdieren zijn welkom.
						Het huis is ongeveer 160 m2  groot en staat op 600 m2  eigen grond.
						Er zijn 4 slaapkamers, waarvan 2 slaapkamers op de begane grond en 2 op de 1e verdieping.
						Dit maakt het huis geschikt voor mensen die wat slechter ter been zijn.
					</p>
        </div>
      </article>
    </div>
  </div>
</div>